name: Workflow 2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to Dockerhub"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Conditional Step
        id: conditional
        run: echo "Workflow 2 Started"

      - name: Docker pull Image
        run: |
          docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ github.event.workflow_run.env.${DOCKER_BUILD_VERSION} }}
      - name: Run Docker Container
        run: |
          docker run -d -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ github.event.workflow_run.DOCKER_BUILD_VERSION }} 
          
