name: Workflow 2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to Dockerhub"]
    types:
      - completed

jobs:
  run-container:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Conditional Step
        id: conditional
        run: echo "Workflow 2 Started"
      - name: docker image pull
        run: |
          echo "${{ github.event.workflow_run.conclusion }}"
        
