name: Workflow 2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to Dockerhub"]
    types:
      - completed

jobs:
  run-container:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Conditional Step
        id: conditional
        run: echo "Workflow 2 Started"

      - name: Set up Docker Build Version
        run: |
          echo "DOCKER_BUILD_VERSION=${{ needs.build-and-push.outputs.DOCKER_BUILD_VERSION }}" > ${{DOCKER_BUILD_VERSION}}
      - name: Run Docker Container
        run: |
          docker run -d -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{DOCKER_BUILD_VERSION}}
        
