name: Workflow 2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to Dockerhub"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Conditional Step
        id: conditional
        run: echo "Workflow 2 Started"

      
      - name: Docker Image Pull
        run: |
           docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}
           docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nginx:
      - name: Docker Container Run
        run: |
           docker run -d --name nginx -p 2355:80 ${{secrets.DOCKERHUB_USERNAME}}/nginx:36
           docker ps
           curl localhost:2355
        
