name: Workflow 2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to Dockerhub"]
    types:
      - completed

jobs:
  run-container:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Conditional Step
        id: conditional
        run: echo "Workflow 2 Started"

      - name: Docker Pull Image
        run: |  
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nginx
          docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/nginx
        
