name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Conditional Step
        id: conditional
        run: echo "Workflow 2 Started"

      - name: Check Workflow 1 Result
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "Workflow 1 succeeded; Workflow 2 continues..."
          else
            echo "Workflow 1 failed; Workflow 2 stops."
            exit 1
          fi
