name: Workfow File Two

# on:
#   push:
#     branches:
#       - master

on:
  workflow_run:
    workflows: ["Workflow1"]
    types:
      - completed

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: SuccessFully Message
        run: echo "Successfully Workflow job2 Using Github Action"
