name: Workflow 2

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Workflow 2
        run: |
          echo "Workflow 2 Successfullt"
