# File: pull_image_and_run_workflow.yml

name: Pull and Run Docker Image

on:
  workflow_run:
    workflows: ["Push Docker Image to Dockerhub"]
    types:
      - completed

jobs:
  pull-and-run-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Conditional Step
        id: conditional
        run: echo "Workflow 2 Started"

      - name: Docker Image Pull
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${DOCKER_BUILD_VERSION}
      
      - name: Run Docker Container
        run: |
          docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${DOCKER_BUILD_VERSION}
